// Pulled stills live in assets/. Add a line here after each pull. Do not hotlink Google Photos.
// Regenerated by scripts/import-looks.py from assets/library.
window.AshlieeLooks = {
  hero: [
    {
      src: "assets/hero.jpg",
      alt: "Editorial portrait of Ashliee Moore surrounded by red roses",
      caption: "Look 01 — Roses",
    },
    {
      src: "assets/fashion-06.jpg",
      alt: "Ashliee in a chartreuse gown with oversized ruffle sleeves",
      caption: "Look 02 — Chartreuse",
    },
    {
      src: "assets/fashion-04.jpg",
      alt: "Ashliee in a crimson blazer editorial with crystal jewelry",
      caption: "Look 03 — Crimson",
    },
    {
      src: "assets/fashion-08.jpg",
      alt: "Ashliee walking an outdoor night runway in a black blazer and tulle",
      caption: "Look 04 — Night walk",
    },
    {
      src: "assets/library/fashion/000.jpg",
      alt: "Ashliee Moore — Look 000",
      caption: "Look 000",
    },
    {
      src: "assets/library/fashion/001.jpg",
      alt: "Ashliee Moore — Look 001",
      caption: "Look 001",
    },
    {
      src: "assets/library/fashion/002.jpg",
      alt: "Ashliee Moore — Look 002",
      caption: "Look 002",
    },
    {
      src: "assets/library/fashion/003.jpg",
      alt: "Ashliee Moore — Look 003",
      caption: "Look 003",
    },
    {
      src: "assets/library/fashion/004.jpg",
      alt: "Ashliee Moore — Look 004",
      caption: "Look 004",
    },
    {
      src: "assets/library/fashion/006.jpg",
      alt: "Ashliee Moore — Look 006",
      caption: "Look 006",
    },
    {
      src: "assets/library/fashion/007.jpg",
      alt: "Ashliee Moore — Look 007",
      caption: "Look 007",
    },
    {
      src: "assets/library/fashion/008.jpg",
      alt: "Ashliee Moore — Look 008",
      caption: "Look 008",
    },
    {
      src: "assets/library/fashion/009.jpg",
      alt: "Ashliee Moore — Look 009",
      caption: "Look 009",
    },
    {
      src: "assets/library/fashion/011.jpg",
      alt: "Ashliee Moore — Look 011",
      caption: "Look 011",
    },
    {
      src: "assets/library/fashion/013.jpg",
      alt: "Ashliee Moore — Look 013",
      caption: "Look 013",
    },
    {
      src: "assets/library/fashion/014.jpg",
      alt: "Ashliee Moore — Look 014",
      caption: "Look 014",
    },
    {
      src: "assets/library/fashion/015.jpg",
      alt: "Ashliee Moore — Look 015",
      caption: "Look 015",
    },
    {
      src: "assets/library/fashion/016.jpg",
      alt: "Ashliee Moore — Look 016",
      caption: "Look 016",
    },
    {
      src: "assets/library/fashion/017.jpg",
      alt: "Ashliee Moore — Look 017",
      caption: "Look 017",
    },
    {
      src: "assets/library/fashion/018.jpg",
      alt: "Ashliee Moore — Look 018",
      caption: "Look 018",
    },
    {
      src: "assets/library/fashion/019.jpg",
      alt: "Ashliee Moore — Look 019",
      caption: "Look 019",
    },
    {
      src: "assets/library/fashion/020.jpg",
      alt: "Ashliee Moore — Look 020",
      caption: "Look 020",
    },
    {
      src: "assets/library/fashion/021.jpg",
      alt: "Ashliee Moore — Look 021",
      caption: "Look 021",
    },
    {
      src: "assets/library/fashion/022.jpg",
      alt: "Ashliee Moore — Look 022",
      caption: "Look 022",
    },
    {
      src: "assets/library/fashion/023.jpg",
      alt: "Ashliee Moore — Look 023",
      caption: "Look 023",
    },
    {
      src: "assets/library/fashion/024.jpg",
      alt: "Ashliee Moore — Look 024",
      caption: "Look 024",
    },
    {
      src: "assets/library/fashion/025.jpg",
      alt: "Ashliee Moore — Look 025",
      caption: "Look 025",
    },
    {
      src: "assets/library/fashion/026.jpg",
      alt: "Ashliee Moore — Look 026",
      caption: "Look 026",
    },
    {
      src: "assets/library/fashion/027.jpg",
      alt: "Ashliee Moore — Look 027",
      caption: "Look 027",
    },
    {
      src: "assets/library/fashion/028.jpg",
      alt: "Ashliee Moore — Look 028",
      caption: "Look 028",
    },
    {
      src: "assets/library/fashion/029.jpg",
      alt: "Ashliee Moore — Look 029",
      caption: "Look 029",
    },
    {
      src: "assets/library/fashion/030.jpg",
      alt: "Ashliee Moore — Look 030",
      caption: "Look 030",
    },
    {
      src: "assets/library/fashion/031.jpg",
      alt: "Ashliee Moore — Look 031",
      caption: "Look 031",
    },
    {
      src: "assets/library/fashion/032.jpg",
      alt: "Ashliee Moore — Look 032",
      caption: "Look 032",
    },
    {
      src: "assets/library/fashion/033.jpg",
      alt: "Ashliee Moore — Look 033",
      caption: "Look 033",
    },
    {
      src: "assets/library/fashion/034.jpg",
      alt: "Ashliee Moore — Look 034",
      caption: "Look 034",
    },
    {
      src: "assets/library/fashion/035.jpg",
      alt: "Ashliee Moore — Look 035",
      caption: "Look 035",
    },
    {
      src: "assets/library/fashion/036.jpg",
      alt: "Ashliee Moore — Look 036",
      caption: "Look 036",
    },
    {
      src: "assets/library/fashion/037.jpg",
      alt: "Ashliee Moore — Look 037",
      caption: "Look 037",
    },
    {
      src: "assets/library/fashion/038.jpg",
      alt: "Ashliee Moore — Look 038",
      caption: "Look 038",
    },
    {
      src: "assets/library/fashion/039.jpg",
      alt: "Ashliee Moore — Look 039",
      caption: "Look 039",
    },
    {
      src: "assets/library/fashion/040.jpg",
      alt: "Ashliee Moore — Look 040",
      caption: "Look 040",
    },
    {
      src: "assets/library/fashion/041.jpg",
      alt: "Ashliee Moore — Look 041",
      caption: "Look 041",
    },
    {
      src: "assets/library/fashion/042.jpg",
      alt: "Ashliee Moore — Look 042",
      caption: "Look 042",
    },
    {
      src: "assets/library/fashion/043.jpg",
      alt: "Ashliee Moore — Look 043",
      caption: "Look 043",
    },
    {
      src: "assets/library/fashion/044.jpg",
      alt: "Ashliee Moore — Look 044",
      caption: "Look 044",
    },
    {
      src: "assets/library/fashion/045.jpg",
      alt: "Ashliee Moore — Look 045",
      caption: "Look 045",
    },
    {
      src: "assets/library/fashion/046.jpg",
      alt: "Ashliee Moore — Look 046",
      caption: "Look 046",
    },
    {
      src: "assets/library/fashion/047.jpg",
      alt: "Ashliee Moore — Look 047",
      caption: "Look 047",
    },
    {
      src: "assets/library/fashion/048.jpg",
      alt: "Ashliee Moore — Look 048",
      caption: "Look 048",
    },
    {
      src: "assets/library/fashion/049.jpg",
      alt: "Ashliee Moore — Look 049",
      caption: "Look 049",
    },
    {
      src: "assets/library/fashion/050.jpg",
      alt: "Ashliee Moore — Look 050",
      caption: "Look 050",
    }
  ],
  runway: [
    {
      src: "assets/runway-01.jpg",
      alt: "Ashliee Moore on the Be ExquisiteU fashion show runway",
      caption: "Be ExquisiteU",
    },
    {
      src: "assets/fashion-08.jpg",
      alt: "Ashliee walking an outdoor night runway in a black blazer and tulle",
      caption: "Night walk",
    },
    {
      src: "assets/fashion-06.jpg",
      alt: "Ashliee in a chartreuse gown with oversized ruffle sleeves",
      caption: "Chartreuse",
    },
    {
      src: "assets/fashion-07.jpg",
      alt: "Ashliee peeking over a chartreuse ruffle sleeve on the runway",
      caption: "Over the ruffle",
    },
    {
      src: "assets/fashion-04.jpg",
      alt: "Ashliee in a crimson blazer editorial with crystal jewelry",
      caption: "Crimson hour",
    },
    {
      src: "assets/runway-02.jpg",
      alt: "Ashliee in a two-piece fashion look",
      caption: "Two-piece",
    },
    {
      src: "assets/runway-03.jpg",
      alt: "Ashliee in a colorful evening mini dress on a city night street",
      caption: "City night",
    },
    {
      src: "assets/runway-04.jpg",
      alt: "Ashliee styled in handmade fashion for Sac Fashion Pro",
      caption: "Sac Fashion Pro",
    },
    {
      src: "assets/fashion-01.jpg",
      alt: "Ashliee walking a night street runway as the audience watches",
      caption: "Street runway",
    },
    {
      src: "assets/library/fashion/000.jpg",
      alt: "Ashliee Moore — Look 000",
      caption: "Look 000",
    },
    {
      src: "assets/library/fashion/001.jpg",
      alt: "Ashliee Moore — Look 001",
      caption: "Look 001",
    },
    {
      src: "assets/library/fashion/003.jpg",
      alt: "Ashliee Moore — Look 003",
      caption: "Look 003",
    },
    {
      src: "assets/library/fashion/004.jpg",
      alt: "Ashliee Moore — Look 004",
      caption: "Look 004",
    },
    {
      src: "assets/library/fashion/006.jpg",
      alt: "Ashliee Moore — Look 006",
      caption: "Look 006",
    },
    {
      src: "assets/library/fashion/007.jpg",
      alt: "Ashliee Moore — Look 007",
      caption: "Look 007",
    },
    {
      src: "assets/library/fashion/008.jpg",
      alt: "Ashliee Moore — Look 008",
      caption: "Look 008",
    },
    {
      src: "assets/library/fashion/009.jpg",
      alt: "Ashliee Moore — Look 009",
      caption: "Look 009",
    },
    {
      src: "assets/library/fashion/011.jpg",
      alt: "Ashliee Moore — Look 011",
      caption: "Look 011",
    },
    {
      src: "assets/library/fashion/014.jpg",
      alt: "Ashliee Moore — Look 014",
      caption: "Look 014",
    },
    {
      src: "assets/library/fashion/015.jpg",
      alt: "Ashliee Moore — Look 015",
      caption: "Look 015",
    },
    {
      src: "assets/library/fashion/016.jpg",
      alt: "Ashliee Moore — Look 016",
      caption: "Look 016",
    },
    {
      src: "assets/library/fashion/017.jpg",
      alt: "Ashliee Moore — Look 017",
      caption: "Look 017",
    },
    {
      src: "assets/library/fashion/018.jpg",
      alt: "Ashliee Moore — Look 018",
      caption: "Look 018",
    },
    {
      src: "assets/library/fashion/019.jpg",
      alt: "Ashliee Moore — Look 019",
      caption: "Look 019",
    },
    {
      src: "assets/library/fashion/020.jpg",
      alt: "Ashliee Moore — Look 020",
      caption: "Look 020",
    },
    {
      src: "assets/library/fashion/021.jpg",
      alt: "Ashliee Moore — Look 021",
      caption: "Look 021",
    },
    {
      src: "assets/library/fashion/022.jpg",
      alt: "Ashliee Moore — Look 022",
      caption: "Look 022",
    },
    {
      src: "assets/library/fashion/023.jpg",
      alt: "Ashliee Moore — Look 023",
      caption: "Look 023",
    },
    {
      src: "assets/library/fashion/024.jpg",
      alt: "Ashliee Moore — Look 024",
      caption: "Look 024",
    },
    {
      src: "assets/library/fashion/025.jpg",
      alt: "Ashliee Moore — Look 025",
      caption: "Look 025",
    },
    {
      src: "assets/library/fashion/026.jpg",
      alt: "Ashliee Moore — Look 026",
      caption: "Look 026",
    },
    {
      src: "assets/library/fashion/027.jpg",
      alt: "Ashliee Moore — Look 027",
      caption: "Look 027",
    },
    {
      src: "assets/library/fashion/028.jpg",
      alt: "Ashliee Moore — Look 028",
      caption: "Look 028",
    },
    {
      src: "assets/library/fashion/029.jpg",
      alt: "Ashliee Moore — Look 029",
      caption: "Look 029",
    },
    {
      src: "assets/library/fashion/030.jpg",
      alt: "Ashliee Moore — Look 030",
      caption: "Look 030",
    },
    {
      src: "assets/library/fashion/031.jpg",
      alt: "Ashliee Moore — Look 031",
      caption: "Look 031",
    },
    {
      src: "assets/library/fashion/032.jpg",
      alt: "Ashliee Moore — Look 032",
      caption: "Look 032",
    },
    {
      src: "assets/library/fashion/033.jpg",
      alt: "Ashliee Moore — Look 033",
      caption: "Look 033",
    },
    {
      src: "assets/library/fashion/034.jpg",
      alt: "Ashliee Moore — Look 034",
      caption: "Look 034",
    },
    {
      src: "assets/library/fashion/035.jpg",
      alt: "Ashliee Moore — Look 035",
      caption: "Look 035",
    },
    {
      src: "assets/library/fashion/036.jpg",
      alt: "Ashliee Moore — Look 036",
      caption: "Look 036",
    },
    {
      src: "assets/library/fashion/037.jpg",
      alt: "Ashliee Moore — Look 037",
      caption: "Look 037",
    },
    {
      src: "assets/library/fashion/038.jpg",
      alt: "Ashliee Moore — Look 038",
      caption: "Look 038",
    },
    {
      src: "assets/library/fashion/039.jpg",
      alt: "Ashliee Moore — Look 039",
      caption: "Look 039",
    },
    {
      src: "assets/library/fashion/040.jpg",
      alt: "Ashliee Moore — Look 040",
      caption: "Look 040",
    },
    {
      src: "assets/library/fashion/041.jpg",
      alt: "Ashliee Moore — Look 041",
      caption: "Look 041",
    },
    {
      src: "assets/library/fashion/042.jpg",
      alt: "Ashliee Moore — Look 042",
      caption: "Look 042",
    },
    {
      src: "assets/library/fashion/043.jpg",
      alt: "Ashliee Moore — Look 043",
      caption: "Look 043",
    },
    {
      src: "assets/library/fashion/044.jpg",
      alt: "Ashliee Moore — Look 044",
      caption: "Look 044",
    },
    {
      src: "assets/library/fashion/045.jpg",
      alt: "Ashliee Moore — Look 045",
      caption: "Look 045",
    },
    {
      src: "assets/library/fashion/046.jpg",
      alt: "Ashliee Moore — Look 046",
      caption: "Look 046",
    },
    {
      src: "assets/library/fashion/047.jpg",
      alt: "Ashliee Moore — Look 047",
      caption: "Look 047",
    },
    {
      src: "assets/library/fashion/048.jpg",
      alt: "Ashliee Moore — Look 048",
      caption: "Look 048",
    },
    {
      src: "assets/library/fashion/049.jpg",
      alt: "Ashliee Moore — Look 049",
      caption: "Look 049",
    },
    {
      src: "assets/library/fashion/050.jpg",
      alt: "Ashliee Moore — Look 050",
      caption: "Look 050",
    }
  ],
  glam: [
    {
      src: "assets/glam-01.jpg",
      alt: "Black and white beauty close-up of Ashliee in a denim jacket",
      caption: "Denim, unbothered",
    },
    {
      src: "assets/glam-03.jpg",
      alt: "Beauty portrait of Ashliee with magenta eyeshadow and red lipstick",
      caption: "Magenta hour",
    },
    {
      src: "assets/glam-02.jpg",
      alt: "Black and white portrait of Ashliee with graphic square jewelry",
      caption: "Dice & ink",
    },
    {
      src: "assets/profile.jpg",
      alt: "Beauty close-up of Ashliee in a grey fur hat",
      caption: "Fur hour",
    },
    {
      src: "assets/library/cosmetology/000.jpg",
      alt: "Ashliee Moore — Glam 000",
      caption: "Glam 000",
    },
    {
      src: "assets/library/cosmetology/001.jpg",
      alt: "Ashliee Moore — Glam 001",
      caption: "Glam 001",
    },
    {
      src: "assets/library/cosmetology/002.jpg",
      alt: "Ashliee Moore — Glam 002",
      caption: "Glam 002",
    },
    {
      src: "assets/library/cosmetology/003.jpg",
      alt: "Ashliee Moore — Glam 003",
      caption: "Glam 003",
    }
  ],
  tasting: [
    {
      src: "assets/kitchen-02.jpg",
      alt: "Plated lobster tail with roasted lemon on a charcoal dish",
      caption: "The plate",
    },
    {
      src: "assets/kitchen-03.jpg",
      alt: "King crab, lobster, and garlic bread on a red platter",
      caption: "The catch",
    },
    {
      src: "assets/kitchen-06.jpg",
      alt: "Prawn, mussels, and clams over linguine in a red sauce",
      caption: "Linguine",
    },
    {
      src: "assets/kitchen-05.jpg",
      alt: "Blackened salmon with rosemary, peppers, and lemon",
      caption: "Blackened",
    },
    {
      src: "assets/kitchen-04.jpg",
      alt: "Crab boil in a dutch oven with a glass of red wine",
      caption: "The boil",
    },
    {
      src: "assets/library/culinary/000.jpg",
      alt: "Ashliee Moore — Plate 000",
      caption: "Plate 000",
    },
    {
      src: "assets/library/culinary/001.jpg",
      alt: "Ashliee Moore — Plate 001",
      caption: "Plate 001",
    },
    {
      src: "assets/library/culinary/002.jpg",
      alt: "Ashliee Moore — Plate 002",
      caption: "Plate 002",
    },
    {
      src: "assets/library/culinary/003.jpg",
      alt: "Ashliee Moore — Plate 003",
      caption: "Plate 003",
    },
    {
      src: "assets/library/culinary/004.jpg",
      alt: "Ashliee Moore — Plate 004",
      caption: "Plate 004",
    },
    {
      src: "assets/library/culinary/005.jpg",
      alt: "Ashliee Moore — Plate 005",
      caption: "Plate 005",
    },
    {
      src: "assets/library/culinary/006.jpg",
      alt: "Ashliee Moore — Plate 006",
      caption: "Plate 006",
    },
    {
      src: "assets/library/culinary/007.jpg",
      alt: "Ashliee Moore — Plate 007",
      caption: "Plate 007",
    },
    {
      src: "assets/library/culinary/008.jpg",
      alt: "Ashliee Moore — Plate 008",
      caption: "Plate 008",
    },
    {
      src: "assets/library/culinary/009.jpg",
      alt: "Ashliee Moore — Plate 009",
      caption: "Plate 009",
    },
    {
      src: "assets/library/culinary/010.jpg",
      alt: "Ashliee Moore — Plate 010",
      caption: "Plate 010",
    },
    {
      src: "assets/library/culinary/011.jpg",
      alt: "Ashliee Moore — Plate 011",
      caption: "Plate 011",
    },
    {
      src: "assets/library/culinary/012.jpg",
      alt: "Ashliee Moore — Plate 012",
      caption: "Plate 012",
    },
    {
      src: "assets/library/culinary/013.jpg",
      alt: "Ashliee Moore — Plate 013",
      caption: "Plate 013",
    },
    {
      src: "assets/library/culinary/014.jpg",
      alt: "Ashliee Moore — Plate 014",
      caption: "Plate 014",
    },
    {
      src: "assets/library/culinary/015.jpg",
      alt: "Ashliee Moore — Plate 015",
      caption: "Plate 015",
    },
    {
      src: "assets/library/culinary/016.jpg",
      alt: "Ashliee Moore — Plate 016",
      caption: "Plate 016",
    },
    {
      src: "assets/library/culinary/017.jpg",
      alt: "Ashliee Moore — Plate 017",
      caption: "Plate 017",
    },
    {
      src: "assets/library/culinary/018.jpg",
      alt: "Ashliee Moore — Plate 018",
      caption: "Plate 018",
    },
    {
      src: "assets/library/culinary/019.jpg",
      alt: "Ashliee Moore — Plate 019",
      caption: "Plate 019",
    },
    {
      src: "assets/library/culinary/020.jpg",
      alt: "Ashliee Moore — Plate 020",
      caption: "Plate 020",
    },
    {
      src: "assets/library/culinary/021.jpg",
      alt: "Ashliee Moore — Plate 021",
      caption: "Plate 021",
    },
    {
      src: "assets/library/culinary/022.jpg",
      alt: "Ashliee Moore — Plate 022",
      caption: "Plate 022",
    },
    {
      src: "assets/library/culinary/023.jpg",
      alt: "Ashliee Moore — Plate 023",
      caption: "Plate 023",
    },
    {
      src: "assets/library/culinary/024.jpg",
      alt: "Ashliee Moore — Plate 024",
      caption: "Plate 024",
    },
    {
      src: "assets/library/culinary/025.jpg",
      alt: "Ashliee Moore — Plate 025",
      caption: "Plate 025",
    },
    {
      src: "assets/library/culinary/026.jpg",
      alt: "Ashliee Moore — Plate 026",
      caption: "Plate 026",
    },
    {
      src: "assets/library/culinary/027.jpg",
      alt: "Ashliee Moore — Plate 027",
      caption: "Plate 027",
    },
    {
      src: "assets/library/culinary/028.jpg",
      alt: "Ashliee Moore — Plate 028",
      caption: "Plate 028",
    },
    {
      src: "assets/library/culinary/029.jpg",
      alt: "Ashliee Moore — Plate 029",
      caption: "Plate 029",
    },
    {
      src: "assets/library/culinary/030.jpg",
      alt: "Ashliee Moore — Plate 030",
      caption: "Plate 030",
    },
    {
      src: "assets/library/culinary/031.jpg",
      alt: "Ashliee Moore — Plate 031",
      caption: "Plate 031",
    },
    {
      src: "assets/library/culinary/032.jpg",
      alt: "Ashliee Moore — Plate 032",
      caption: "Plate 032",
    },
    {
      src: "assets/library/culinary/033.jpg",
      alt: "Ashliee Moore — Plate 033",
      caption: "Plate 033",
    },
    {
      src: "assets/library/culinary/034.jpg",
      alt: "Ashliee Moore — Plate 034",
      caption: "Plate 034",
    }
  ],
  scene: [
    {
      src: "assets/scene-01.jpg",
      alt: "Ashliee representing LiBush Africa fashion and culture",
      caption: "LiBush Africa",
    },
    {
      src: "assets/scene-02.jpg",
      alt: "Ashliee at a birthday-themed night event look",
      caption: "Night presence",
    },
    {
      src: "assets/scene-03.jpg",
      alt: "Studio portrait collaboration with VVS Studios in downtown Sacramento",
      caption: "VVS Studios",
    },
    {
      src: "assets/scene-04.jpg",
      alt: "Ashliee in a pink lace dress during a sunset shoot",
      caption: "Sunset editorial",
    },
    {
      src: "assets/library/events/000.jpg",
      alt: "Ashliee Moore — Scene 000",
      caption: "Scene 000",
    },
    {
      src: "assets/library/events/001.jpg",
      alt: "Ashliee Moore — Scene 001",
      caption: "Scene 001",
    },
    {
      src: "assets/library/events/002.jpg",
      alt: "Ashliee Moore — Scene 002",
      caption: "Scene 002",
    },
    {
      src: "assets/library/events/003.jpg",
      alt: "Ashliee Moore — Scene 003",
      caption: "Scene 003",
    },
    {
      src: "assets/library/events/004.jpg",
      alt: "Ashliee Moore — Scene 004",
      caption: "Scene 004",
    },
    {
      src: "assets/library/events/005.jpg",
      alt: "Ashliee Moore — Scene 005",
      caption: "Scene 005",
    },
    {
      src: "assets/library/events/006.jpg",
      alt: "Ashliee Moore — Scene 006",
      caption: "Scene 006",
    }
  ]
};
