// Pulled stills live in assets/. Add a line here after each pull. Do not hotlink Google Photos.
// Regenerated by scripts/import-looks.py from assets/library (+ captions.json when present).
window.AshlieeLooks = {
  hero: [
    {
      src: "assets/hero.jpg",
      alt: "Editorial portrait of Ashliee Moore surrounded by red roses",
      caption: "Look 01 — Roses",
    },
    {
      src: "assets/fashion-06.jpg",
      alt: "Ashliee in a chartreuse gown with oversized ruffle sleeves",
      caption: "Look 02 — Chartreuse",
    },
    {
      src: "assets/fashion-04.jpg",
      alt: "Ashliee in a crimson blazer editorial with crystal jewelry",
      caption: "Look 03 — Crimson",
    },
    {
      src: "assets/fashion-08.jpg",
      alt: "Ashliee walking an outdoor night runway in a black blazer and tulle",
      caption: "Look 04 — Night walk",
    },
    {
      src: "assets/library/fashion/000.jpg",
      alt: "Ashliee kneeling on the beach in a seafoam gown with a gold sunburst headpiece",
      caption: "Halo shore",
    },
    {
      src: "assets/library/fashion/001.jpg",
      alt: "Ashliee in an aqua evening gown",
      caption: "Aqua gown",
    },
    {
      src: "assets/library/fashion/002.jpg",
      alt: "Ashliee in a dramatic red cape look",
      caption: "Red cape",
    },
    {
      src: "assets/library/fashion/003.jpg",
      alt: "Ashliee in a velvet evening look",
      caption: "Velvet night",
    },
    {
      src: "assets/library/fashion/004.jpg",
      alt: "Ashliee in a gold editorial look",
      caption: "Gold hour",
    },
    {
      src: "assets/library/fashion/006.jpg",
      alt: "Ashliee walking a night street runway",
      caption: "Street stride",
    },
    {
      src: "assets/library/fashion/007.jpg",
      alt: "Ashliee in a sharp blazer fashion look",
      caption: "Blazer cut",
    },
    {
      src: "assets/library/fashion/008.jpg",
      alt: "Ashliee in tulle on the runway",
      caption: "Tulle lift",
    },
    {
      src: "assets/library/fashion/009.jpg",
      alt: "Ashliee styled with crystal jewelry",
      caption: "Crystal light",
    },
    {
      src: "assets/library/fashion/011.jpg",
      alt: "Ashliee on a rooftop fashion set",
      caption: "Rooftop wind",
    },
    {
      src: "assets/library/fashion/013.jpg",
      alt: "Ashliee in a bold print look",
      caption: "Print play",
    },
    {
      src: "assets/library/fashion/014.jpg",
      alt: "Ashliee in a structured coat look",
      caption: "Coat check",
    },
    {
      src: "assets/library/fashion/015.jpg",
      alt: "Ashliee in a floral evening dress",
      caption: "Night floral",
    },
    {
      src: "assets/library/fashion/016.jpg",
      alt: "Ashliee pausing mid-walk on the runway",
      caption: "Runway pause",
    },
    {
      src: "assets/library/fashion/017.jpg",
      alt: "Editorial side profile of Ashliee",
      caption: "Side profile",
    },
    {
      src: "assets/library/fashion/018.jpg",
      alt: "Ashliee glancing back in a fashion look",
      caption: "Back glance",
    },
    {
      src: "assets/library/fashion/019.jpg",
      alt: "Full-length fashion still of Ashliee",
      caption: "Hemline",
    },
    {
      src: "assets/library/fashion/021.jpg",
      alt: "Ashliee under stage lights",
      caption: "Stage light",
    },
    {
      src: "assets/library/fashion/022.jpg",
      alt: "Close editorial portrait of Ashliee",
      caption: "Editorial stare",
    },
    {
      src: "assets/library/fashion/023.jpg",
      alt: "Ashliee mid-movement in a fashion look",
      caption: "Motion blur",
    },
    {
      src: "assets/library/fashion/024.jpg",
      alt: "Ashliee in a sequined fashion look",
      caption: "Sequin hour",
    },
    {
      src: "assets/library/fashion/025.jpg",
      alt: "Ashliee in a soft power fashion look",
      caption: "Soft power",
    },
    {
      src: "assets/library/fashion/026.jpg",
      alt: "Ashliee styled with statement headpiece",
      caption: "Crown work",
    },
    {
      src: "assets/library/fashion/027.jpg",
      alt: "Ashliee in an outdoor beach editorial",
      caption: "Beach editorial",
    },
    {
      src: "assets/library/fashion/028.jpg",
      alt: "Ashliee on a location fashion set",
      caption: "Ladder set",
    },
    {
      src: "assets/library/fashion/029.jpg",
      alt: "Ashliee walking with audience in frame",
      caption: "Crowd walk",
    },
    {
      src: "assets/library/fashion/030.jpg",
      alt: "Ashliee posing in a fashion look",
      caption: "Mirror pose",
    },
    {
      src: "assets/library/fashion/031.jpg",
      alt: "Ashliee in a color-blocked outfit",
      caption: "Color block",
    },
    {
      src: "assets/library/fashion/032.jpg",
      alt: "Ashliee in a satin fashion look",
      caption: "Satin line",
    },
    {
      src: "assets/library/fashion/033.jpg",
      alt: "Ashliee in a leather-edged look",
      caption: "Leather edge",
    },
    {
      src: "assets/library/fashion/034.jpg",
      alt: "Ashliee in a high-contrast white look",
      caption: "White heat",
    },
    {
      src: "assets/library/fashion/035.jpg",
      alt: "Ashliee in an all-black fashion look",
      caption: "Blackout",
    },
    {
      src: "assets/library/fashion/036.jpg",
      alt: "Ashliee in pink lace",
      caption: "Pink lace",
    },
    {
      src: "assets/library/fashion/037.jpg",
      alt: "Ashliee in a yellow Time Capsule look",
      caption: "Yellow flash",
    },
    {
      src: "assets/library/fashion/038.jpg",
      alt: "Ashliee in an orange print look",
      caption: "Orange print",
    },
    {
      src: "assets/library/fashion/039.jpg",
      alt: "Ashliee in a plaid coat look",
      caption: "Plaid coat",
    },
    {
      src: "assets/library/fashion/040.jpg",
      alt: "Ashliee in a green hat fashion look",
      caption: "Green hat",
    },
    {
      src: "assets/library/fashion/041.jpg",
      alt: "Ashliee in a flowing maxi look",
      caption: "Maxi flow",
    },
    {
      src: "assets/library/fashion/042.jpg",
      alt: "Ashliee in a night mini dress",
      caption: "Mini night",
    },
    {
      src: "assets/library/fashion/043.jpg",
      alt: "Ashliee in a two-piece fashion set",
      caption: "Two-piece set",
    },
    {
      src: "assets/library/fashion/044.jpg",
      alt: "Ashliee in a handmade fashion look",
      caption: "Handmade",
    },
    {
      src: "assets/library/fashion/045.jpg",
      alt: "Ashliee in a Getty red-carpet style look",
      caption: "Getty red",
    },
    {
      src: "assets/library/fashion/046.jpg",
      alt: "Ashliee in a Time Capsule fashion look",
      caption: "Time Capsule",
    },
    {
      src: "assets/library/fashion/047.jpg",
      alt: "Ashliee on the Be ExquisiteU runway",
      caption: "ExquisiteU",
    },
    {
      src: "assets/library/fashion/048.jpg",
      alt: "Ashliee at Sac Fashion Pro",
      caption: "Sac Pro",
    },
    {
      src: "assets/library/fashion/049.jpg",
      alt: "Ashliee in black blazer and tulle",
      caption: "Night tulle",
    },
    {
      src: "assets/library/fashion/050.jpg",
      alt: "Ashliee in chartreuse ruffle sleeves",
      caption: "Chartreuse wing",
    }
  ],
  runway: [
    {
      src: "assets/runway-01.jpg",
      alt: "Ashliee Moore on the Be ExquisiteU fashion show runway",
      caption: "Be ExquisiteU",
    },
    {
      src: "assets/fashion-08.jpg",
      alt: "Ashliee walking an outdoor night runway in a black blazer and tulle",
      caption: "Night walk",
    },
    {
      src: "assets/fashion-06.jpg",
      alt: "Ashliee in a chartreuse gown with oversized ruffle sleeves",
      caption: "Chartreuse",
    },
    {
      src: "assets/fashion-07.jpg",
      alt: "Ashliee peeking over a chartreuse ruffle sleeve on the runway",
      caption: "Over the ruffle",
    },
    {
      src: "assets/fashion-04.jpg",
      alt: "Ashliee in a crimson blazer editorial with crystal jewelry",
      caption: "Crimson hour",
    },
    {
      src: "assets/runway-02.jpg",
      alt: "Ashliee in a two-piece fashion look",
      caption: "Two-piece",
    },
    {
      src: "assets/runway-03.jpg",
      alt: "Ashliee in a colorful evening mini dress on a city night street",
      caption: "City night",
    },
    {
      src: "assets/runway-04.jpg",
      alt: "Ashliee styled in handmade fashion for Sac Fashion Pro",
      caption: "Sac Fashion Pro",
    },
    {
      src: "assets/fashion-01.jpg",
      alt: "Ashliee walking a night street runway as the audience watches",
      caption: "Street runway",
    },
    {
      src: "assets/library/fashion/000.jpg",
      alt: "Ashliee kneeling on the beach in a seafoam gown with a gold sunburst headpiece",
      caption: "Halo shore",
    },
    {
      src: "assets/library/fashion/001.jpg",
      alt: "Ashliee in an aqua evening gown",
      caption: "Aqua gown",
    },
    {
      src: "assets/library/fashion/003.jpg",
      alt: "Ashliee in a dramatic red cape look",
      caption: "Red cape",
    },
    {
      src: "assets/library/fashion/004.jpg",
      alt: "Ashliee in a velvet evening look",
      caption: "Velvet night",
    },
    {
      src: "assets/library/fashion/006.jpg",
      alt: "Ashliee in a gold editorial look",
      caption: "Gold hour",
    },
    {
      src: "assets/library/fashion/007.jpg",
      alt: "Ashliee walking a night street runway",
      caption: "Street stride",
    },
    {
      src: "assets/library/fashion/008.jpg",
      alt: "Ashliee in a sharp blazer fashion look",
      caption: "Blazer cut",
    },
    {
      src: "assets/library/fashion/009.jpg",
      alt: "Ashliee in tulle on the runway",
      caption: "Tulle lift",
    },
    {
      src: "assets/library/fashion/011.jpg",
      alt: "Ashliee styled with crystal jewelry",
      caption: "Crystal light",
    },
    {
      src: "assets/library/fashion/014.jpg",
      alt: "Ashliee on a rooftop fashion set",
      caption: "Rooftop wind",
    },
    {
      src: "assets/library/fashion/015.jpg",
      alt: "Ashliee in a bold print look",
      caption: "Print play",
    },
    {
      src: "assets/library/fashion/016.jpg",
      alt: "Ashliee in a structured coat look",
      caption: "Coat check",
    },
    {
      src: "assets/library/fashion/017.jpg",
      alt: "Ashliee in a floral evening dress",
      caption: "Night floral",
    },
    {
      src: "assets/library/fashion/018.jpg",
      alt: "Ashliee pausing mid-walk on the runway",
      caption: "Runway pause",
    },
    {
      src: "assets/library/fashion/019.jpg",
      alt: "Editorial side profile of Ashliee",
      caption: "Side profile",
    },
    {
      src: "assets/library/fashion/021.jpg",
      alt: "Ashliee glancing back in a fashion look",
      caption: "Back glance",
    },
    {
      src: "assets/library/fashion/022.jpg",
      alt: "Full-length fashion still of Ashliee",
      caption: "Hemline",
    },
    {
      src: "assets/library/fashion/023.jpg",
      alt: "Ashliee under stage lights",
      caption: "Stage light",
    },
    {
      src: "assets/library/fashion/024.jpg",
      alt: "Close editorial portrait of Ashliee",
      caption: "Editorial stare",
    },
    {
      src: "assets/library/fashion/025.jpg",
      alt: "Ashliee mid-movement in a fashion look",
      caption: "Motion blur",
    },
    {
      src: "assets/library/fashion/026.jpg",
      alt: "Ashliee in a sequined fashion look",
      caption: "Sequin hour",
    },
    {
      src: "assets/library/fashion/027.jpg",
      alt: "Ashliee in a soft power fashion look",
      caption: "Soft power",
    },
    {
      src: "assets/library/fashion/028.jpg",
      alt: "Ashliee styled with statement headpiece",
      caption: "Crown work",
    },
    {
      src: "assets/library/fashion/029.jpg",
      alt: "Ashliee in an outdoor beach editorial",
      caption: "Beach editorial",
    },
    {
      src: "assets/library/fashion/030.jpg",
      alt: "Ashliee on a location fashion set",
      caption: "Ladder set",
    },
    {
      src: "assets/library/fashion/031.jpg",
      alt: "Ashliee walking with audience in frame",
      caption: "Crowd walk",
    },
    {
      src: "assets/library/fashion/032.jpg",
      alt: "Ashliee posing in a fashion look",
      caption: "Mirror pose",
    },
    {
      src: "assets/library/fashion/033.jpg",
      alt: "Ashliee in a color-blocked outfit",
      caption: "Color block",
    },
    {
      src: "assets/library/fashion/034.jpg",
      alt: "Ashliee in a satin fashion look",
      caption: "Satin line",
    },
    {
      src: "assets/library/fashion/035.jpg",
      alt: "Ashliee in a leather-edged look",
      caption: "Leather edge",
    },
    {
      src: "assets/library/fashion/036.jpg",
      alt: "Ashliee in a high-contrast white look",
      caption: "White heat",
    },
    {
      src: "assets/library/fashion/037.jpg",
      alt: "Ashliee in an all-black fashion look",
      caption: "Blackout",
    },
    {
      src: "assets/library/fashion/038.jpg",
      alt: "Ashliee in pink lace",
      caption: "Pink lace",
    },
    {
      src: "assets/library/fashion/039.jpg",
      alt: "Ashliee in a yellow Time Capsule look",
      caption: "Yellow flash",
    },
    {
      src: "assets/library/fashion/040.jpg",
      alt: "Ashliee in an orange print look",
      caption: "Orange print",
    },
    {
      src: "assets/library/fashion/041.jpg",
      alt: "Ashliee in a plaid coat look",
      caption: "Plaid coat",
    },
    {
      src: "assets/library/fashion/042.jpg",
      alt: "Ashliee in a green hat fashion look",
      caption: "Green hat",
    },
    {
      src: "assets/library/fashion/043.jpg",
      alt: "Ashliee in a flowing maxi look",
      caption: "Maxi flow",
    },
    {
      src: "assets/library/fashion/044.jpg",
      alt: "Ashliee in a night mini dress",
      caption: "Mini night",
    },
    {
      src: "assets/library/fashion/045.jpg",
      alt: "Ashliee in a two-piece fashion set",
      caption: "Two-piece set",
    },
    {
      src: "assets/library/fashion/046.jpg",
      alt: "Ashliee in a handmade fashion look",
      caption: "Handmade",
    },
    {
      src: "assets/library/fashion/047.jpg",
      alt: "Ashliee in a Getty red-carpet style look",
      caption: "Getty red",
    },
    {
      src: "assets/library/fashion/048.jpg",
      alt: "Ashliee in a Time Capsule fashion look",
      caption: "Time Capsule",
    },
    {
      src: "assets/library/fashion/049.jpg",
      alt: "Ashliee on the Be ExquisiteU runway",
      caption: "ExquisiteU",
    },
    {
      src: "assets/library/fashion/050.jpg",
      alt: "Ashliee at Sac Fashion Pro",
      caption: "Sac Pro",
    }
  ],
  glam: [
    {
      src: "assets/glam-01.jpg",
      alt: "Black and white beauty close-up of Ashliee in a denim jacket",
      caption: "Denim, unbothered",
    },
    {
      src: "assets/glam-03.jpg",
      alt: "Beauty portrait of Ashliee with magenta eyeshadow and red lipstick",
      caption: "Magenta hour",
    },
    {
      src: "assets/glam-02.jpg",
      alt: "Black and white portrait of Ashliee with graphic square jewelry",
      caption: "Dice & ink",
    },
    {
      src: "assets/library/cosmetology/000.jpg",
      alt: "Black and white beauty close-up of Ashliee in a denim jacket",
      caption: "Denim close",
    },
    {
      src: "assets/library/cosmetology/001.jpg",
      alt: "Beauty portrait of Ashliee with polished soft glam makeup",
      caption: "Soft glam",
    },
    {
      src: "assets/library/cosmetology/002.jpg",
      alt: "Close-up beauty still highlighting lashes and finish",
      caption: "Lash hour",
    },
    {
      src: "assets/library/cosmetology/003.jpg",
      alt: "Beauty portrait of Ashliee with a full glam look",
      caption: "Full face",
    }
  ],
  tasting: [
    {
      src: "assets/kitchen-02.jpg",
      alt: "Plated lobster tail with roasted lemon on a charcoal dish",
      caption: "The plate",
    },
    {
      src: "assets/kitchen-03.jpg",
      alt: "King crab, lobster, and garlic bread on a red platter",
      caption: "The catch",
    },
    {
      src: "assets/kitchen-06.jpg",
      alt: "Prawn, mussels, and clams over linguine in a red sauce",
      caption: "Linguine",
    },
    {
      src: "assets/kitchen-05.jpg",
      alt: "Blackened salmon with rosemary, peppers, and lemon",
      caption: "Blackened",
    },
    {
      src: "assets/kitchen-04.jpg",
      alt: "Crab boil in a dutch oven with a glass of red wine",
      caption: "The boil",
    },
    {
      src: "assets/library/culinary/000.jpg",
      alt: "Seasoned salmon fillets with rosemary, peppers, onion, and lemon in a glass baking dish",
      caption: "Rosemary salmon",
    },
    {
      src: "assets/library/culinary/001.jpg",
      alt: "Seared salmon topped with lemon, glazed carrots, and a creamy side salad",
      caption: "Lemon sear",
    },
    {
      src: "assets/library/culinary/002.jpg",
      alt: "Seasoned beef strips and peppers sizzling in a pan",
      caption: "Pan heat",
    },
    {
      src: "assets/library/culinary/003.jpg",
      alt: "Pan-seared steak tips with seasoned shrimp, corn, green beans, and rice",
      caption: "Surf & turf",
    },
    {
      src: "assets/library/culinary/006.jpg",
      alt: "Linguine in red sauce with mussels, clams, shrimp, and a whole prawn",
      caption: "Seafood linguine",
    },
    {
      src: "assets/library/culinary/007.jpg",
      alt: "Herb-crusted fish with lemon, sausage-topped mashed potatoes, and broccoli",
      caption: "Herb fillet",
    },
    {
      src: "assets/library/culinary/009.jpg",
      alt: "Spice-rubbed chicken with lemon, garlic, peppers, and green onion in a glass dish",
      caption: "Lemon garlic chicken",
    },
    {
      src: "assets/library/culinary/011.jpg",
      alt: "Sautéed cabbage with onions and bell peppers in a pan",
      caption: "Cabbage sauté",
    },
    {
      src: "assets/library/culinary/012.jpg",
      alt: "Foil packets of shrimp with lemon and sausage with corn on the grill",
      caption: "Grill packets",
    },
    {
      src: "assets/library/culinary/013.jpg",
      alt: "A dish prepped for the oven",
      caption: "Oven ready",
    },
    {
      src: "assets/library/culinary/014.jpg",
      alt: "Food hitting a hot pan",
      caption: "Pan sear",
    },
    {
      src: "assets/library/culinary/015.jpg",
      alt: "A plated dish finished with citrus",
      caption: "Citrus finish",
    },
    {
      src: "assets/library/culinary/016.jpg",
      alt: "A hosted table spread",
      caption: "Host table",
    },
    {
      src: "assets/library/culinary/017.jpg",
      alt: "A family-style serving",
      caption: "Family style",
    },
    {
      src: "assets/library/culinary/018.jpg",
      alt: "Cooking over heat",
      caption: "Fire side",
    },
    {
      src: "assets/library/culinary/019.jpg",
      alt: "Fresh ingredients in prep",
      caption: "Fresh prep",
    },
    {
      src: "assets/library/culinary/020.jpg",
      alt: "Sauce finishing a plate",
      caption: "Sauce work",
    },
    {
      src: "assets/library/culinary/021.jpg",
      alt: "Shellfish plated for service",
      caption: "Shell game",
    },
    {
      src: "assets/library/culinary/022.jpg",
      alt: "Herbs finishing a dish",
      caption: "Herb lift",
    },
    {
      src: "assets/library/culinary/023.jpg",
      alt: "A late-night plated service",
      caption: "Night service",
    },
    {
      src: "assets/library/culinary/024.jpg",
      alt: "A dish at the kitchen pass",
      caption: "Kitchen pass",
    },
    {
      src: "assets/library/culinary/025.jpg",
      alt: "A guest-ready plated meal",
      caption: "Guest plate",
    },
    {
      src: "assets/library/culinary/026.jpg",
      alt: "A hot dish with rising steam",
      caption: "Steam rise",
    },
    {
      src: "assets/library/culinary/027.jpg",
      alt: "Prep on the cutting board",
      caption: "Chop board",
    },
    {
      src: "assets/library/culinary/028.jpg",
      alt: "Food in a cast-iron vessel",
      caption: "Cast iron",
    },
    {
      src: "assets/library/culinary/029.jpg",
      alt: "A dish in a glass baking dish",
      caption: "Glass bake",
    },
    {
      src: "assets/library/culinary/030.jpg",
      alt: "A red-sauce pasta plate",
      caption: "Red sauce",
    },
    {
      src: "assets/library/culinary/031.jpg",
      alt: "Citrus and heat on a plated fish",
      caption: "Lemon heat",
    },
    {
      src: "assets/library/culinary/032.jpg",
      alt: "A crab-forward seafood plate",
      caption: "Crab night",
    },
    {
      src: "assets/library/culinary/033.jpg",
      alt: "A lobster plating",
      caption: "Lobster hour",
    },
    {
      src: "assets/library/culinary/034.jpg",
      alt: "Seafood with garlic bread",
      caption: "Garlic bread",
    }
  ],
  scene: [
    {
      src: "assets/scene-01.jpg",
      alt: "Ashliee representing LiBush Africa fashion and culture",
      caption: "LiBush Africa",
    },
    {
      src: "assets/scene-02.jpg",
      alt: "Ashliee at a birthday-themed night event look",
      caption: "Night presence",
    },
    {
      src: "assets/scene-03.jpg",
      alt: "Studio portrait collaboration with VVS Studios in downtown Sacramento",
      caption: "VVS Studios",
    },
    {
      src: "assets/scene-04.jpg",
      alt: "Ashliee in a pink lace dress during a sunset shoot",
      caption: "Sunset editorial",
    },
    {
      src: "assets/library/events/000.jpg",
      alt: "Black and white group editorial with Ashliee centered in denim",
      caption: "Ensemble lead",
    },
    {
      src: "assets/library/events/001.jpg",
      alt: "Ashliee in a tiered fuzzy look posing with a companion in studio",
      caption: "Studio duo",
    },
    {
      src: "assets/library/events/002.jpg",
      alt: "Behind-the-scenes energy from a location shoot",
      caption: "Shoot day",
    },
    {
      src: "assets/library/events/003.jpg",
      alt: "Editorial group in denim and orange tulle in a parking garage",
      caption: "Garage tulle",
    },
    {
      src: "assets/library/events/004.jpg",
      alt: "Ashliee on a rooftop or outdoor event set",
      caption: "Rooftop call",
    },
    {
      src: "assets/library/events/005.jpg",
      alt: "Ashliee representing brand presence at an event",
      caption: "Brand room",
    },
    {
      src: "assets/library/events/006.jpg",
      alt: "Ashliee in an after-hours event look",
      caption: "After glow",
    }
  ]
};
