DELETE FROM look;

INSERT INTO look (section, src, alt, caption, sort_order) VALUES
('hero', '/media/hero.jpg', 'Editorial portrait of Ashliee Moore surrounded by red roses', 'Look 01 — Roses', 1),
('hero', '/media/fashion-06.jpg', 'Outdoors, a model in black lace and a metallic gold ruffled collar holds a large bouquet of pink and white chrysanthemums.', 'Garden ruff', 2),
('hero', '/media/fashion-04.jpg', 'A model in a yellow damask hoodie, brown textured pants, and cream train leans against a bold black-white-and-orange mural.', 'Mural profile', 3),
('hero', '/media/fashion-08.jpg', 'Ashliee walking an outdoor night runway in a black blazer and tulle', 'Look 04 — Night walk', 4),
('hero', '/media/library/fashion/000.jpg', 'A model kneels on dark sand in a seafoam beaded gown and golden sunburst crown, one hand extended toward the water.', 'Gilded shores', 5),
('hero', '/media/library/fashion/006.jpg', 'A black-and-white close-up of a woman in a denim jacket with dramatic lashes, groomed brows, and slicked baby hairs.', 'Ink portrait', 6),
('hero', '/media/library/fashion/008.jpg', 'A woman in a black faux-leather shirt-dress sits in a wingback chair beside pampas grass under moody purple-tinted light.', 'Leather repose', 7),
('hero', '/media/library/fashion/011.jpg', 'A beauty close-up shows pink glitter eyeshadow, matte red lips, and gold rings against a grey backdrop and burgundy velvet neckline.', 'Velvet shimmer', 8),
('hero', '/media/library/fashion/012.jpg', 'On a dim runway, a model wears a neon yellow dress with towering pleated ruffles framing her face and curly updo.', 'Citron bloom', 9),
('hero', '/media/library/fashion/013.jpg', 'A model peeks over massive neon yellow ruffles of a sculptural gown, looking back over her shoulder on a dark runway.', 'Tiered citron', 10),
('hero', '/media/library/fashion/017.jpg', 'Low-key light casts a sharp profile shadow of a woman with gold shimmer makeup, long straight hair, and a magenta top.', 'Magenta hour', 11),
('hero', '/media/library/fashion/035.jpg', 'On a reflective runway beside a vintage locomotive, a model wears a black tulle crop top and colorful printed maxi skirt.', 'Engine stride', 12),
('hero', '/media/library/fashion/036.jpg', 'A model in a black off-shoulder tulle top and geometric print maxi skirt poses in front of a dark steam engine with red wheels.', 'Tulle and steam', 13),
('runway', '/media/runway-01.jpg', 'Ashliee Moore on the Be ExquisiteU fashion show runway', 'Be ExquisiteU', 1),
('runway', '/media/fashion-08.jpg', 'Ashliee walking an outdoor night runway in a black blazer and tulle', 'Night walk', 2),
('runway', '/media/fashion-06.jpg', 'Outdoors, a model in black lace and a metallic gold ruffled collar holds a large bouquet of pink and white chrysanthemums.', 'Garden ruff', 3),
('runway', '/media/fashion-07.jpg', 'A model peeks over massive neon yellow ruffles of a sculptural gown, looking back over her shoulder on a dark runway.', 'Tiered citron', 4),
('runway', '/media/fashion-04.jpg', 'A model in a yellow damask hoodie, brown textured pants, and cream train leans against a bold black-white-and-orange mural.', 'Mural profile', 5),
('runway', '/media/runway-02.jpg', 'Ashliee in an aqua evening gown', 'Aqua gown', 6),
('runway', '/media/runway-03.jpg', 'Ashliee in a colorful evening mini dress on a city night street', 'City night', 7),
('runway', '/media/runway-04.jpg', 'A woman in a black faux-leather shirt-dress sits in a wingback chair beside pampas grass under moody purple-tinted light.', 'Leather repose', 8),
('runway', '/media/fashion-01.jpg', 'Ashliee walking a night street runway as the audience watches', 'Street runway', 9),
('runway', '/media/library/fashion/006.jpg', 'A black-and-white close-up of a woman in a denim jacket with dramatic lashes, groomed brows, and slicked baby hairs.', 'Ink portrait', 10),
('runway', '/media/library/fashion/011.jpg', 'A beauty close-up shows pink glitter eyeshadow, matte red lips, and gold rings against a grey backdrop and burgundy velvet neckline.', 'Velvet shimmer', 11),
('runway', '/media/library/fashion/017.jpg', 'Low-key light casts a sharp profile shadow of a woman with gold shimmer makeup, long straight hair, and a magenta top.', 'Magenta hour', 12),
('runway', '/media/library/fashion/035.jpg', 'On a reflective runway beside a vintage locomotive, a model wears a black tulle crop top and colorful printed maxi skirt.', 'Engine stride', 13),
('runway', '/media/library/fashion/036.jpg', 'A model in a black off-shoulder tulle top and geometric print maxi skirt poses in front of a dark steam engine with red wheels.', 'Tulle and steam', 14),
('glam', '/media/glam-01.jpg', 'Black and white beauty close-up of Ashliee in a denim jacket', 'Denim, unbothered', 1),
('glam', '/media/glam-03.jpg', 'Beauty portrait of Ashliee with magenta eyeshadow and red lipstick', 'Magenta hour', 2),
('glam', '/media/glam-02.jpg', 'A beauty close-up shows pink glitter eyeshadow, matte red lips, and gold rings against a grey backdrop and burgundy velvet neckline.', 'Velvet shimmer', 3),
('glam', '/media/library/cosmetology/003.jpg', 'On a runway, a model looks over her shoulder through neon yellow ruffles, revealing bold eye makeup and a high puff with bangs.', 'Neon peek', 4),
('tasting', '/media/kitchen-02.jpg', 'Plated lobster tail with roasted lemon on a charcoal dish', 'The plate', 1),
('tasting', '/media/kitchen-03.jpg', 'King crab, lobster, and garlic bread on a red platter', 'The catch', 2),
('tasting', '/media/kitchen-06.jpg', 'Prawn, mussels, and clams over linguine in a red sauce', 'Linguine', 3),
('tasting', '/media/kitchen-05.jpg', 'Blackened salmon with rosemary, peppers, and lemon', 'Blackened', 4),
('tasting', '/media/kitchen-04.jpg', 'Crab boil in a dutch oven with a glass of red wine', 'The boil', 5),
('tasting', '/media/library/culinary/000.jpg', 'Two seasoned salmon fillets with rosemary sit in a glass dish over sliced peppers, onion, and lemon on a stovetop.', 'Rosemary salmon', 6),
('tasting', '/media/library/culinary/007.jpg', 'A green rectangular plate holds a seasoned fish fillet with lemon, mashed potatoes with sausage, and steamed broccoli.', 'Green plate supper', 7),
('tasting', '/media/library/culinary/009.jpg', 'Raw chicken pieces in a glass dish are rubbed with spice, garlic, scallions, bell peppers, and a row of lemon slices.', 'Lemon lined chicken', 8),
('tasting', '/media/library/culinary/020.jpg', 'A frying pan simmers with okra, onion, lemon and lime wedges, melting butter, and chopped herbs.', 'Citrus butter pan', 9),
('tasting', '/media/library/culinary/021.jpg', 'Snow crab legs and lobster tails rest in colanders inside a stainless sink beside packaged shellfish.', 'Shell rinse', 10),
('tasting', '/media/library/culinary/027.jpg', 'Snow crab legs bubble in a teal Dutch oven while a blurred glass of red wine fills the foreground.', 'Wine and crab', 11),
('tasting', '/media/library/culinary/028.jpg', 'A patterned red bowl overflows with crab legs, lobster, shrimp, parsley, lemon, and garlic bread on granite.', 'Red bowl feast', 12),
('tasting', '/media/library/culinary/031.jpg', 'Produce, almond milk, eggs, and supplement bottles are arranged on a gray kitchen counter by the stove.', 'Market morning', 13),
('tasting', '/media/library/culinary/033.jpg', 'On a black etched plate, lobster tail and penne in golden sauce are garnished with scallions, microgreens, and grilled lemon.', 'Lobster penne', 14),
('scene', '/media/scene-01.jpg', 'In black and white, a woman in a buttoned denim jacket stands centered among four softly blurred figures behind her.', 'Denim ensemble', 1),
('scene', '/media/scene-02.jpg', 'Ashliee at a birthday-themed night event look', 'Night presence', 2),
('scene', '/media/scene-03.jpg', 'On a reflective runway beside a vintage locomotive, a model wears a black tulle crop top and colorful printed maxi skirt.', 'Engine stride', 3),
('scene', '/media/scene-05.jpg', 'On a wet rooftop lot, Ashliee in a long denim coat, red gloves, and red thigh boots leans against a gold ladder.', 'Rooftop denim', 4),
('kitchen', '/media/kitchen-01.jpg', 'Ashliee Moore hosting at a Sacramento sushi and hibachi restaurant, smiling and pointing toward the camera', 'The host', 1),
('about', '/media/about-02.jpg', 'Editorial portrait of Ashliee Moore surrounded by red roses', 'Roses', 1);
